name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt 
          pip install -r docs/requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          folder: _build
